### ISSUE TITLE
Home Page:  'Subscribe' button click should automatically scroll down to subscribe section.

### ISSUE THREAD

**Issue by Linjith** [tekcapsule/tekcapsule-web#13]
Currently nothing happens when you click on 'Subscribe' button in the home page carousel.

**Comment by AdithyaPrabhu** [comment]
29106e5bb18af9b62d807c8e4d50b9e28e694d45

**Comment by AdithyaPrabhu** [comment]
completed .

commit - 29106e5bb18af9b62d807c8e4d50b9e28e694d45
