### ISSUE TITLE
Home page: Create a page to show terms of use and link in the footer

### ISSUE THREAD

**Issue by Linjith** [tekcapsule/tekcapsule-web#19]

**Comment by AdithyaPrabhu** [comment]
@Linjith - shall i get some generic wording off the internet ?

**Comment by AdithyaPrabhu** [comment]
6e5ce4f0122d4903451e51932cd1232f4488543e
created separate module & routes for this static html pages
 updated the text to the one provided by Linjith 
css changes pending

**Comment by AdithyaPrabhu** [comment]
closing this as there is a separate ticket created just for css changes
https://github.com/tekcapsule/tekcapsule-web/issues/58
